name: mssql
services:
    server:
        environment:
            - ACCEPT_EULA=Y
            - "MSSQL_SA_PASSWORD=yourStrong(!)Password"
        ports:
            - "127.0.0.1:1433:1433"
        volumes:
            - ./mssql:/var/opt/mssql/data
        container_name: sqlpreview
        hostname: sqlpreview
        image: mcr.microsoft.com/mssql/server:2019-latest